# Generated by Django 5.0.7 on 2024-07-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everapp', '0030_livechat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveChat',
        ),
    ]
